version: '3.7'
services:
  bayes-subscriber:
    networks:
      - default
    container_name: event-driven-bayes-bayes
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    platform: "linux/amd64"
    env_file:
      - .env
      # - local.env
    volumes:
      - .:/event-driven-bayes
    depends_on:
      - redis
    command: ["./entrypoint.sh", "bayes"]

  api-publisher:
    networks:
      - default
    container_name: event-driven-bayes-api
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    platform: "linux/amd64"
    env_file:
      - .env
      # - local.env
    ports:
      - "8000:${PORT:-8000}"
    volumes:
      - .:/event-driven-bayes
    depends_on:
      - redis
    command: ["./entrypoint.sh", "api"]

  jupyter:
    container_name: event-driven-bayes-jupyter
    build:
      context: .
      dockerfile: Dockerfile
    platform: "linux/amd64"
    ports:
      - "8888:8888"
    volumes:
      - .:/event-driven-bayes
    command: ["./entrypoint.sh", "jupyter"]

  redis:
    networks:
      - default
    container_name: event-driven-bayes-redis
    image: redis:6-alpine
    ports:
      - "6381:6379"
